name: Catch2 EXample

on:
  workflow_dispatch: # lets you run a build from the UI

env:
  BUILD_TYPE: Release
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CMAKE_BUILD_PARALLEL_LEVEL: 3 # Use up to 3 cpus to build juceaide, etc
  HOMEBREW_NO_INSTALL_CLEANUP: 1

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run C++ benchmark example
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and run benchmarks with Catch2
        run: |
          git submodule update --init
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --target Benchmarks --config Release
          ./Benchmarks | tee ../benchmark_result.txt