name: Catch2 C++ Example
on:
  workflow_dispatch: # lets you run a build from the UI
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run C++ benchmark example
    runs-on: macOS
    steps:
      - uses: actions/checkout@v4
      - name: Build and run benchmarks with Catch2
        run: |
          sudo apt-get install libxrandr-dev
          git submodule update --init
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release
          ./build/Benchmarks | tee benchmark_result.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Catch2 Benchmark
          tool: 'catch2'
          output-file-path: benchmark_result.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@wwerkk'

      - name: Store benchmark result - separate results repo
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Catch2 Benchmark
          tool: 'catch2'
          output-file-path: benchmark_result.txt
          github-token: ${{ secrets.BENCHMARK_ACTION_BOT_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@wwerkk'
          gh-repository: 'https://github.com/wwerkk/dummyjuce'
