name: GH Pages PR Debug
# Do not run this workflow on pull request since this workflow has permission to modify contents.
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

env:
    BUILD_TYPE: Release
    CMAKE_BUILD_PARALLEL_LEVEL: 3 # Use up to 3 cpus to build juceaide, etc
    HOMEBREW_NO_INSTALL_CLEANUP: 1

jobs:
  benchmark:
    name: Run benchmark and store results
    runs-on: macos-latest
    steps:
      # - uses: actions/checkout@v4
      # - name: Build and run Catch2 bench
      #   run: |
      #     git submodule update --init
      #     mkdir build && cd build
      #     cmake -DCMAKE_BUILD_TYPE=Release ..
      #     cmake --build . --target Benchmarks --config Release
      #     ./Benchmarks | tee ../benchmark_result.txt

      - name: Parse output file and push to Pages
        uses: INA-grm/github-action-benchmark@v0.2.19-wip 
        with:
          name: Dummy JUCE Project Benchmark
          tool: "catch2"
          output-file-path: benchmark_result.txt
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
